### ISSUE TITLE
Dashboard shows incorrect state for a build

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/testgrid#1136]
**Description:**

![image](https://user-images.githubusercontent.com/29540334/50967903-801b4e80-14ff-11e9-932f-96285a03a39d.png)

Even though in the history its show as a failed build, in the description it is shown as a currently running build. 

**Steps to reproduce:**

https://testgrid-live.private.wso2.com/wso2am-intg/prod-wso2am-intg-deployment/test-plans/wso2am-intg_prod-wso2am-intg-deployment_CentOS-7.5_OpenJDK-8_MySQL-5.7_run2
**Related Issues:**

**Comment by pasindujw** [comment]
This is fixed now. Hence closing..
