### ISSUE TITLE
Email-alerts for TestGrid jobs shows incorrect failure types

### ISSUE THREAD

**Issue by KosalaHerath** [wso2/testgrid#1142]
**Description:**

Although the tests are failed due to tests issues the email-alert shows that are due to infrastructure failures. 
Following image shows how email present infrastructure errors. 
 ![test2](https://user-images.githubusercontent.com/33099111/51964413-83658280-248c-11e9-9266-98adb3408e8f.png)

However, the these failures are happen due to the test failures as shown in below. (for OPEN_JDK8, Ubuntu-18.04, SQLServer-SE-14.00)

![testg1](https://user-images.githubusercontent.com/33099111/51964460-a55f0500-248c-11e9-9dad-1e67a0d111b6.png)

**Related Email:**

[DEV][UNSTABLE] 'wum-sce-test-wso2am-2.6.0-full' Test Results! #(12)

**Comment by kasunbg** [comment]
@pasindujw @sameerawickramasekara can you check this. We need to do an immediate fix?

**Comment by pasindujw** [comment]
Not present as per @ctienshi. Hence closing.
