### ISSUE TITLE
Maven build dir 'target' considered as a scenario module

### ISSUE THREAD

**Issue by praminda** [wso2/testgrid#1148]
**Description:**

TG treats the Maven build output dir `target` of root `product-scenarios` module as a scenario module and looks for some artefacts in there. This causes the build to be identified as `unstable`, even if all tests are passing.
Suggested solution: Skip Maven build directory `target` from being traversed as an scenario module.
**Suggested Labels:**
Priority/High
Type/Improvement

**Comment by kasunbg** [comment]
A fix has been sent to dev/prod. You should see correct behavior in newer builds.

pr: https://github.com/wso2/testgrid/pull/1147/files

**Comment by praminda** [comment]
+1. Thanks for the fix
