### ISSUE TITLE
TestGrid cannot find the surefire report file in certain scenarios

### ISSUE THREAD

**Issue by Manuri** [wso2/testgrid#1178]
**Description:**
$Subject occurs when the testng.xml is configured with classes instead of packages.

eg:
```xml
        <classes>
            <class name="org.ballerinalang.scenario.test.http.HttpCircuitBreakerScenarioTest" />
        </classes>
```
In this case, the surefire test result xml is created with the name 
"TEST-org.ballerinalang.scenario.test.http.HttpCircuitBreakerScenarioTest.xml" instead of 
"TEST-TestSuite.xml", therefore TestGrid doesn't find it.

**Comment by kasunbg** [comment]
This is now fixed. Thanks for reporting.
