### ISSUE TITLE
Testgrid dashboard integration success test count is incorrect

### ISSUE THREAD

**Issue by aaujayasena** [wso2/testgrid#1185]
Type:Bug
Severity: Critical
Priority: Highest

Incorrect pass success count display at the dashboard for IS integration test .[1]
Expected result: Count display as 609
Actual result: Count is 1224

[1] https://testgrid-live-dev.private.wso2.com/achini-wso2is-intg

**Comment by kasunbg** [comment]
This is now fixed via #1196. Thanks for reporting.
