### ISSUE TITLE
Evaluate NOSQL as the database storage option 

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#249]
**Description:**

Right now, we are using RDBMS as the database storage mechanism. Here we store,

1. The List of product channels
2. The test-run information of infrastructure combinations for a given product channel
3. The test-run information of scenarios for each infrastructure combination
4. The test-run information of scenario test cases of each scenario.

The infrastructure combination here refers to a list of value-sets defined by the relevant product team. This is usually a combination of OS/JDK/and Database. But, this list may vary. For example, more value-sets can get added to the system - existing value-sets may grow/shrink etc.

As the starting point, we used RDBMS as the storage. But, we need to do a bit of research to find out what is a better way to store this information. Document databases like _MongoDB_ seems like a good fit.

If research shows that NOSQL is a better option, we should convert existing storage to that.

**Comment by kasunbg** [comment]
Good starting point: https://www.sisense.com/blog/postgres-vs-mongodb-for-storing-json-data/

**Comment by pasindujw** [comment]
@kasunbg I hope with the current TG architecture and with our DB purging process , RDBMS fits to the position well. WDYT?

**Comment by kasunbg** [comment]
Yes, +1.
