### ISSUE TITLE
Provide a build progress bar when a testplan runs

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#288]
**Description:**

Currently, we have to look at the logs to find the status of a currently running build. We need to show a progress bar to show the progress.

See the following for the first draft:

![image](https://user-images.githubusercontent.com/936037/34476576-f584fdf6-efb7-11e7-94a6-9ae7df90c96b.png)

**Comment by pasindujw** [comment]
Resolved with introducing test phases.
