### ISSUE TITLE
'No log4j2 configuration file found' shown in TestGrid testruns

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#293]
**Description:**
TestGrid Jenkins testplan builds show following error.

```
ERROR StatusLogger No log4j2 configuration file found. 
 default configuration: logging only errors to the console. 
Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
```

**Comment by vidurananayakkara** [comment]
Closing this issue since this error can be resolved if we provide the log4j.xml location.

Example: -Dlog4j.configurationFile=/home/viduran/Documents/test-grid/wso2-test-grid/distribution/bin/log4j2.xml

**Comment by kasunbg** [comment]
The default behavior should work without having to provide a log4j configuration.

**Comment by yasassri** [comment]
I think we can solve this, the testgrid executable scripts set the log4j configuration path.
