### ISSUE TITLE
Test Run Artifacts should be archived

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/testgrid#302]
**Description:**
As of now, test run artefacts are created in Jenkins slave. This should be archived via the Jenkins pipeline.

**Comment by kasunbg** [comment]
After this effort, below code [1] will also go away.

[1] https://github.com/wso2-incubator/testgrid/pull/299/files#diff-c1c1bdc225cde8ab35141c125288205aR50

**Comment by vidurananayakkara** [comment]
This will be done via the Jenkins pipeline:aws-steps plugin.

```
// Archive artifacts
withAWS(credentials:'TESTGRID_BOT_CREDENTIALS') {
    // Upload artifacts to S3
    s3Upload(workingDir:"${TESTGRID_HOME}", includePathPattern:"**/*.log, **/*.html", bucket:"jenkins-testrun-artefacts", path:"artifacts/")
}
```

**Comment by kasunbg** [comment]
@vidurananayakkara shall we send the updated pipeline to [1]?

The bucket name contains a typo. It should be `jenkins-testrun-artifacts`.

[1] https://github.com/wso2-incubator/testgrid/blob/master/jenkins-pipelines/Jenkinsfile
