### ISSUE TITLE
Scenario scripts should receive a properties file as an input

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#310]
**Description:**
Currently, the scenarios scripts receive the output of deploy.sh as environment variables. This is a really bad way of feeding information. 

The deployment creation and scenario writing are managed by different teams. Environment variables does not have a structure, and the actual list of items available is unclear to the scenario script writer.

This is a major issue that we need to fix ASAP.

**Related Issues:**
N/A

**Comment by pasindujw** [comment]
This is resolved now.
