### ISSUE TITLE
Implement support to execute test-runs parallely.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#317]
**Description:**
As you see in [1], we are currently executing the product test-runs for each infrastructure combination sequentially. 

As the number of infrastructure and new infrastructure dimensions are introduced, possible number of infrastructure combinations can be really high. Hence, we need to execute the test-runs in parallel, and scale the TestGrid deployment to accommodate that.

[1] https://github.com/wso2-incubator/testgrid/blob/master/jenkins-pipelines/Jenkinsfile#L71

**Suggested Labels:**

**Suggested Assignees:**

**Related Issues:**
N/A

**Comment by pasindujw** [comment]
This is completed now.
