### ISSUE TITLE
Support execution of Deployment script

### ISSUE THREAD

**Issue by yasassri** [wso2/testgrid#336]
**Description:**
Under the current implementation, only a single script is allowed to run. But we need to execute infra-provision.sh and deploy.sh both to create the infrastructure. This needs to be supported.

**Suggested Labels:**
improvement

**Affected Product Version:**
0.9 M7

**Comment by sameerawickramasekara** [comment]
There is a Deployer class already defined as AWSDeployer. IMO deployer.sh execution can be handled here.

**Comment by kasunbg** [comment]
The deployment script (the deploy.sh) should get executed independent of how the infra provisioning and scenario execution script is executed. 

Infra provisioning can b executed with a infra.sh/cloudformation/(kubernetes)/... providers, and scenario execution can happen thru jmeter/(testng)/(selenium). Likewise, deployment execution can happen thru deploy.sh/(puppet)/(ansible). Direct puppet and Ansible execution support can come later.

**Comment by harshanL** [comment]
Resolved with PR #507.
