### ISSUE TITLE
TestGrid need to honor return status code of infra/deploy scripts.

### ISSUE THREAD

**Issue by yasassri** [wso2/testgrid#337]
**Description:**
After the infrastructure creation is executed, if infrastructure creation fails the execution flow should abort, if deployment scripts fail, scenario execution should abort. We need to support this.

**Suggested Labels:**
Bug

**Comment by azinneera** [comment]
At the moment, #540 enabled gracefully handling failures in each step. Can we define the infra/deploy scripts to return an exit code of 1 if infra creation fails? If so, we can continue from thereon and set the status of infra/deployment provision and the rest will be handled by changes introduced in #540.

**Comment by harshanL** [comment]
IMO scripts should return a proper exit code based on execution result.

**Comment by kasunbg** [comment]
@azinneera +1. What's the current behavior when the exit code is non-zero?

**Comment by azinneera** [comment]
ShellExecutor#executeCommand() returns false if the code is non-zero. Deployment provisioning handles this correctly by setting the status to false. Infra provisioning is missing this which we can incorporate.

**Comment by harshanL** [comment]
+1 for adding the same for Infra provisioning.
