### ISSUE TITLE
Jmeter Execution fails for solution 02

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/testgrid#340]
**Description:**

The latest version of Solution 02 fails with this message
IMO this is due to an external plugin requirement that is not handled through programmatic execution of JMeter.

`Problem loading XML from:'/home/sameera/Identity-test-integration/mint-repo/identity-test-integration/solution02/src/test/jmeter/tmp-01-Soulution-02-Facebook.jmx', missing class com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jorphan.collections.ListedHashTree
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree[4]/hashTree[2]/JSR223Sampler
line number         : 1198
version             : 3.2 r1790748Problem loading XML from:'/home/sameera/Identity-test-integration/mint-repo/identity-test-integration/solution02/src/test/jmeter/tmp-01-Soulution-02-Facebook.jmx', missing class com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jorphan.collections.ListedHashTree
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree[4]/hashTree[2]/JSR223Sampler
line number         : 1198
version             : 3.2 r1790748`

**Steps to reproduce**
Debug the execution flow with solution 02 in line 81:JmeterExecutor.java
`testPlanTree = SaveService.loadTree(new File(script));`

**Comment by yasassri** [comment]
Seems other scenarios are also not executing. I'll be having a look into this.
