### ISSUE TITLE
Design execution of scenario tests via an external shell script

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#348]
**Description:**
ATM, TestGrid goes to a deeper level and execute the jmeter scripts. If we are only going to have jmeter scripts, and since the implementation is already there, IMO it is quite straight-forward for TestGrid to execute jmeter on a per-scenario basis, and parse the results.

But, to generalize the scenario execution, we should instead call a shell script, that may be named as `run-scenarios.sh`. The reasons are:

1. We have to pack jmeter plugins inside the TestGrid distribution. That means, whenever scenarios testing require new JMeter plugins, we will have to release testgrid. This is not scalable. 
If we delegate the managing of JMETER_HOME and its plugins to a generic shell script (run-scenarios.sh), then this problem won't be there.

2. Even though QA Labs team is developing tests on jmeter today, they may change it at a latter date. Further, other test frameworks may also come into use like testng, selenium etc. along with jmeter in the future. I understand we have embedded Selenium tests into JMeter itself today. But, a technical/strategic issue may change that fact.   

Because of these reasons, externalizing of jmeter script execution is required. This run-scenarios.sh may be generic enough for all scenario testing, and therefore could be maintained by the TestGrid team itself. The requirement here is to externalize the scenario execution from the TestGrid core. 

**Affected Product Version:**
0.9.0-m9

**Related Issues:**
N/A

**Comment by kasunbg** [comment]
The idea of this effort is to externalize the jmeter execution from TestGrid. Problem is we have directly involved in the actual jmeter execution...

We should rather implement this outside of testgrid repo that knows how to execute jmeter scripts of the WSO2 platform. Jmeter scripting allows use of plugins, allows calling Java classes over BSF etc. So, the jmeter-runner need to take this into account when running jmeter scripts.

We should have a wider discussion and see how to address this issue.

**Comment by pasindujw** [comment]
Closing since this is been fixed now.
