### ISSUE TITLE
Implement new design of the continuous delivery pipeline for TestGrid

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/testgrid#350]
**Description:**
Latest strategy of CD for TestGrid can be found in [1] . Need to implement these changes.

[1] - https://docs.google.com/document/d/1Fu-06SfyxMDYBrKjYRqN4Dwg8JqSI4DPSL0rYSIUHZc/edit?usp=sharing

**Comment by pasindujw** [comment]
With the current TestGrid CICD flow which include executing integration tests in Dev environment, most of the aspects have been covered ATM. Hence closing the issue.

@sameerawickramasekara  The document contains findings of a good research. You are encouraged to write a blog with those content as well :)
