### ISSUE TITLE
We do not need a separate coverage module

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#374]
**Description:**
It is unnecessary to have a separate module to generate the coverage. We should merge and create one testgrid-core module that has the binary and tests with coverage.

https://github.com/wso2/testgrid/tree/master/test/coverage

**Affected Product Version:**
0.9.0-m10

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
https://github.com/wso2/testgrid/tree/master/test/coverage

**Related Issues:**
N/A

**Comment by vidurananayakkara** [comment]
@kasunbg IMO we need to have the coverage module as a separate since coverage is for all the modules and is not apart of the core. WDYT?

**Comment by kasunbg** [comment]
We need to merge all our sub-modules except 'web' and 'distribution' module into one core module. IMO it is not correct to have dao, infra, reporting etc. are just need to be separate java packages, not in separate modules.

**Comment by pasindujw** [comment]
Closing due to low priority and the current repository structure is fixed ATM.
