### ISSUE TITLE
TestGrid dashboard needs a job history view

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/testgrid#375]
**Description:**
Currently, TestGrid dashboard only shows the last build and the last failed build. But there should be a drilled down view showing job history for a particular Infrastructure + deployment pattern combination

**Suggested Labels:**
Type/Improvement
Type/Task
Priority/High

**Suggested Assignees:**
Sameera Wickramasekara

**Affected Product Version:**
0.9.0-m10

**Comment by kasunbg** [comment]
Discussed wireframe:

![3-job-view-of-a-given-infra-combination](https://user-images.githubusercontent.com/936037/35230516-3f6f5a42-ffbc-11e7-8639-e5e007c681e9.JPG)
