### ISSUE TITLE
IS testplan in production fails with  "--version" is not a valid option

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#392]
**Description:**
IS build of TestGrid production deployment is broken! We need to fix this asap. Since fixing takes time and effort, very first step is to revert any PRs that caused this.

![image](https://user-images.githubusercontent.com/936037/35277675-8b4fb112-006d-11e8-806e-4b817ad1aad3.png)

Even though the build was run two hours ago, the dashboard still shows that the last build was run 5 days ago! I understand the reasons, but this is something we need to fix nevertheless.

![image](https://user-images.githubusercontent.com/936037/35277836-06d0e57c-006e-11e8-8726-1400b8490a06.png)

![image](https://user-images.githubusercontent.com/936037/35277868-21f3ea16-006e-11e8-87f0-06eab3ab1f19.png)

**Suggested Labels:**
N/A

**Suggested Assignees:**
N/A

**Affected Product Version:**
0.9.0-m9

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**

* Error logs can be found here - https://testgrid-live.private.wso2.com/blue/organizations/jenkins/wso2is5.4.0LTS/detail/wso2is5.4.0LTS/3/pipeline

**Related Issues:**

**Comment by yasassri** [comment]
This is fixed in the production environment.

**Comment by yasassri** [comment]
This is tested in prod and dev environment. Hence closing.
