### ISSUE TITLE
Log download link does not work

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#410]
**Description:**

This behavior can be see at: https://testgrid-live-dev.private.wso2.com/testgrid/dashboard/testplans/be52b8e9-af52-43d1-9d22-ee0ef6430f75

![image](https://user-images.githubusercontent.com/936037/35468592-53b7cb54-0347-11e8-9a0e-451e2a9d6edc.png)

**Affected Product Version:**
0.9.0-m10

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
See above.

**Related Issues:**
#409

**Comment by vidurananayakkara** [comment]
This is due to log files are not created in the runtime and hence the log is not uploaded to S3. There is no entry in the S3 bucket with the relevant test plan id.
