### ISSUE TITLE
Provide logs for the dashboard and web api logs.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#411]
**Description:**
There should be an admin view to look at the logs. ATM, where can this be found?

**Affected Product Version:**
0.9.0-m10

**OS, DB, other environment details and versions:**    
N/A
**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by kasunbg** [comment]
I'm turning this into a bug since back-end logs of the dashboard and the web api is nowhere to be found.

**Comment by pasindujw** [comment]
Closing since fixed.
