### ISSUE TITLE
Get cloudformation-is and IS puppet scripts to run against MySQL, Oracle, and Postgres

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#412]
**Description:**
ATM, IS puppet scripts only support MySQL as the back-end database. We need to support at least two more databases to prove TestGrid works properly against multiple infrastructure combinations.

Puppet and cloudformation scripts can be found in below repos respectively:
* https://github.com/wso2/puppet-is
* https://github.com/wso2/cloudformation-is

We need to do the same for operating systems as well. ATM, only Ubuntu is supported. We need to support RHEL/CentOS and Debian. Will need a separate issue for this.

**Affected Product Version:**
0.9.0-m10

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
See above.

**Related Issues:**
N/A

**Comment by harshanL** [comment]
I have added postgres, MariaDB, Oracle and SQLServer support to the IS-Cloudformation fork [1] and tested. Same logic can be reused when integrating it with puppet.

[1]. https://github.com/harshanl/cloudformation-is
