### ISSUE TITLE
Integrate EI deployment scripts into TestGrid

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#416]
**Description:**
  ATM, TestGrid only run the IS scenario testing. To make it certain that this works properly, we need to integrate TestGrid into at lease three products. Chosen ones are: 
* IS 
* APIM 
* EI
  This issue is about integrating EI. 

 Repos: 
 * kubernetes-ei: https://github.com/wso2/kubernetes-ei 
 * cloudformation-ei: https://github.com/wso2/cloudformation-ei
 * puppet-ei: https://github.com/wso2/puppet-ei                                                                                                                                                

**Affected Product Version:**
 0.9.0-m10                                                                                                                       

**OS, DB, other environment details and versions:**
  N/A                                                                                                      
**Steps to reproduce:**
  See above                                                                                                                                     
**Related Issues:**

**Comment by kasunbg** [comment]
I think above repos have not been maintained very well. So, we should draft what's the latest status of these, and send get relevant teams to fix them.

**Comment by kasunbg** [comment]
We need to start the discussion on this ASAP. I think there are not cloudformation scripts for EI. 

I guess, there's a lot to do before we do the integration into testgrid.

**Comment by pasindujw** [comment]
@kasunbg shall we break this into multiple steps and bring them in to milestone since the integration is still at the initial phase? :)

**Comment by kasunbg** [comment]
Sure.. plz do whatever needed to get this done asap.. :)

**Comment by azinneera** [comment]
Since puppet-ei has to be used in cloudformation-ei scripts we do not have anything do from our end. Integration of cloudformation-ei is already resolved and created another issue for kubernetes-ei. Therefore we can close this.
