### ISSUE TITLE
Integrate all IS deployment scripts into TestGrid

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#419]
**Description:**
  ATM, TestGrid only run a limited set of IS scenario testing. It's only run against VM-mode on AWS which is automated via Cloudformation and Puppet. To make it certain that this works properly, we need to integrate TestGrid into at lease three products. Chosen ones are:
 * IS 
*APIM 
*EI  
This issue is about integrating APIM. 

 Repos: 
 * kubernetes: https://github.com/wso2/kubernetes-is 
 * cloudformation: https://github.com/wso2/cloudformation-is
 * puppet: https://github.com/wso2/puppet-is                                                                                                                                                

**Affected Product Version:**
 0.9.0-m10                                                                                                                       

**OS, DB, other environment details and versions:**
  N/A                                                                                                      
**Steps to reproduce:**
  See above                                                                                                                                     
**Related Issues:**
 416, 417, 412

**Comment by azinneera** [comment]
Completed
