### ISSUE TITLE
Test the Testgrid against IS 5.4.1-SNAPSHOT.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#422]
**Description:**
 We have a requirement to verify the IS 5.4.1 scenario testing status. The release is due this Thursday. 
 We need to test it thru TestGrid.                                                                                                                                               

**Affected Product Version:**
 0.9.0-m10                                                                                                                       

**OS, DB, other environment details and versions:**
  N/A                                                                                                      
**Steps to reproduce:**
  See above                                                                                                                                     
**Related Issues:**
 N/A

**Comment by yasassri** [comment]
This is already implemented.
