### ISSUE TITLE
Make the test-run.log file name more context aware.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#430]
**Description:**
  The log file is provided for a given test-run of a given product. I think we can use that information and generate a more context-aware file name.                                                                                                                                              

**Affected Product Version:**
 0.9.0-m10                                                                                                                       

**OS, DB, other environment details and versions:**
  N/A                                                                                                      
**Steps to reproduce:**
  See above                                                                                                                                     
**Related Issues:**
 N/A

**Comment by vidurananayakkara** [comment]
@kasunbg Would <PRODUCT_NAME>_<TIMESTAMP>.log (ex: `wso2-is-5.4.0-lts-2018-02-02 10:32:48.log`) be ok for the file name?

**Comment by kasunbg** [comment]
I was thinking more of <product-name>_<infrastructure-combination/uuid>-<build-number>.log. Daily rolling logs appender in log4j will take care of appending the date to the log file name.

**Comment by azinneera** [comment]
Currently, the _test-run.log_ resides in `<testgrid-home>/<product-name>/<infrastructure-combination-uuid>/<build-number>`

With the name `<product-name>_<infrastructure-combination/uuid>-<build-number>.log` shall we move all the logs to be in this to be in <testgrid-home>/logs?

**Comment by kasunbg** [comment]
Yes, we can.. what's the goal of doing that?

**Comment by azinneera** [comment]
Since the name itself describes it, we do not have to have them in different places. IMO, having all in one place will be easy to refer. WDYT?

**Comment by kasunbg** [comment]
ok.. I think it's better to separate the logs by product job though. So, how about we slighly change your suggestion location to `<testgrid-home>/<product-name>/logs/`?

We can get rid of the product_name from the log file after that.

**Comment by pasindujw** [comment]
Yes as per the above comment, we are now keeping separate storage locations to each testgird job and further to each test-plan. Therefore, as said, we are getting rid of making log-file name context aware since the location of the log-file itself provides the context. Hence closing the issue :)
