### ISSUE TITLE
[Dashboard] Handle UI when no test-runs of a given job were run.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#431]
**Description:**
  See the below to see what I'm trying to say: :) 
![image](https://user-images.githubusercontent.com/936037/35567198-349dfc98-05ea-11e8-92ae-8ef157ec2ed2.png)

As you see, the status is green even though there has been no test-runs for this job.                                                                                                                                              

**Affected Product Version:**
 0.9.0-m10                                                                                                                       

**OS, DB, other environment details and versions:**
  N/A                                                                                                      
**Steps to reproduce:**
  See above                                                                                                                                     
**Related Issues:**
 N/A

**Comment by pasindujw** [comment]
According to the dashboard implementation (Refer:
 [https://github.com/wso2/testgrid/blob/master/web/src/main/react-dashboard/src/components/SingleRecord.js](url) ), this should be automatically fixed with #514

**Comment by harshanL** [comment]
Closed with PR #555.
