### ISSUE TITLE
TestGrid dev dashboard in apps.wso2 is pointing to the wrong URL

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/testgrid#448]
**Description:**
TestGrid dev dashboard in apps.wso2 is pointing to the wrong URL (`https://testgrid-live-dev.private.wso2.com/testgrid/dashboard/api/acs`). This should be (`https://testgrid-live-dev.private.wso2.com/testgrid/dashboard/`)

**Comment by kasunbg** [comment]
This is done now.
