### ISSUE TITLE
Build API should work in both dev and prod.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#458]
**Description:**
ATM, only the dev environment's Build API works. It fails on Prod because it tries to get the job template from the dev. We should make the hostname configurable.                                                                                                                                               

**Affected Product Version:**
 0.9.0-m11                                                                                                                      

**OS, DB, other environment details and versions:**
  N/A                                                                                                      
**Steps to reproduce:**
  See above                                                                                                                                     
**Related Issues:**
 N/A

**Comment by pasindujw** [comment]
Fixed.
Hostname was configurable already. The problem was the hostname "testgrid-live.private.wso2.com" was not resolving as it had not been added to /etc/hosts file.

**Comment by kasunbg** [comment]
How can we make this this won't happen in the future?

**Comment by kasunbg** [comment]
I guess we need to automate the deployment further with a CM tool. Not a priority now. :)

**Comment by pasindujw** [comment]
But this is one-time task for an environment, we don't need to iterate with each new deployment, right?
