### ISSUE TITLE
Inject Spring @PersistenceUnit to concurrently persist to database

### ISSUE THREAD

**Issue by azinneera** [wso2/testgrid#466]
**Description:**
In the current implementation, EntityManager is not thread-safe. The EntityManger should be able to be shared by multiple threads to support concurrent persistence to database. This can be achieved by injecting a persistence unit using @PersistenceUnit in Spring.

**Suggested Labels:**
Type/Improvement

**Comment by pasindujw** [comment]
Closing since there will not be concurrent persistence calls from single TG JVM.
