### ISSUE TITLE
Test case persistence logic should be changed to persist the test scenario and not individual test cases

### ISSUE THREAD

**Issue by azinneera** [wso2/testgrid#474]
**Description:**
Instead of adding test cases to a list in JMeterResultCollector#sampleOccured and then iteratively persisting each test case, it would be appropriate to change the test case persistence logic to add it to the scenario in JMeterResultCollector#sampleOccured and persist the scenario once all the test cases have completed running.

**Suggested Labels:**
Type/Improvement

**Comment by sameerawickramasekara** [comment]
Can you add this issue to m-13 please

**Comment by yasassri** [comment]
@sameerawickramasekara Done.
