### ISSUE TITLE
Get cloudformation-is to run against RHEL 7.x

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#483]
**Description:**
ATM, cloudformation-is is only run against ubuntu as the OS. We need to support at least two more OSes to prove TestGrid works properly against multiple infrastructure combinations.

As the first step, we can add support for RHEL/CentOS.

cloudformation scripts can be found in below repo:
* https://github.com/wso2/cloudformation-is

**Affected Product Version:**
0.9.0-m10

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
See above.

**Related Issues:**
N/A

**Comment by pasindujw** [comment]
This is completed. CF scripts can summon CentOS 7 to be the OS for their node(s).

**Comment by kasunbg** [comment]
Nice, thanks Pasindu.

We can close this once the task is done-done.. :) For that, we need to get the necessary PRs merged, and run CentOS based IS infrastructure tests in testgrid prod deployment. (It is not necessary fix any issue in the underlying deployment creation code. We however need to raise github tickets/mails in relevant repos.)

**Comment by pasindujw** [comment]
ACK. :)

**Comment by kasunbg** [comment]
@pasindujw  Where are we on this. Please keep the pull requests updated.. :)

**Comment by pasindujw** [comment]
@kasunbg the flow is working up to creating stacks. (Which is the end of authority for TestGrid).
PR to add AMI-ID is merged (https://github.com/wso2/cloudformation-is/pull/19)
Necessary CentOS AMIs are added to TestGrid AWS. (#543)

However when there are multiple possible infra-combinations exists, TestGrid is not generating Test-Plan yamls properly (Created issue #558) which blocks getting this infra-combination to dashboard,

**Comment by kasunbg** [comment]
@pasindujw Thanks for the update.

Does the generated test-plans contain the infrastructure combination that you need? ie. at least one combination that has centos?

**Comment by pasindujw** [comment]
@kasunbg no. It always pick UBUNTU as first, and although we have two yalm files which are there as per the reason of having 2 OSs, the second file also has UBUNTU.

**Comment by kasunbg** [comment]
OK, I guess this went unnoticed since we dont have a test case for this. :)

**Comment by harshanL** [comment]
I've raised a git issue on cloudformation-is repo [1] to track.

[1]. https://github.com/wso2/cloudformation-is/issues/22

**Comment by harshanL** [comment]
For now we can use the fork repo [1] to test RHEL deployments.

[1]. https://github.com/harshanL/cloudformation-is

**Comment by kasunbg** [comment]
What's pending on this issue?

**Comment by harshanL** [comment]
Let's wait until the IE team come up with the newer scripts.

**Comment by kasunbg** [comment]
Ok..

Btw, I think we missed to highlight the fact that each OS require its own AMI. Shall we make sure IE team is aware of that? 

CC @ctienshi

**Comment by harshanL** [comment]
The document I've provided him has that information. So shouldn't be a problem.
