### ISSUE TITLE
TestGrid should support config-set changes to the deployment

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/testgrid#484]
**Description:**
During the scenario execution, there is a requirement to change certain configurations of the deployment.
for example, a certain scenario can require the product to have certain configurations present in order to succeed.
These config-sets per scenario will be provided by the STL team. TestGrid needs to implement the support to perform these changes to the deployed product.

**Suggested Labels:**
Type/New feature
Priority/High

**Comment by kasunbg** [comment]
This is tracked via #465.
