### ISSUE TITLE
Error when creating multiple AWS stacks which uses same IS CF template.

### ISSUE THREAD

**Issue by pasindujw** [wso2/testgrid#487]
**Description:**
Occurred with cloudformation-IS script [1]. When trying to create a second stack which uses the same template the task stopped with saying,
load-balancer "identity-demo" already exists (Not the exact words saw in error).
Once modified the second stack's template's load-balancer name, the error was gone.

But it should be possible to run multiple stacks without manually editing the template.

**Suggested Labels:**
Type/Bug 

**Affected Product Version:**
TestGrid-v0.90-m12-Snapshot

**OS, DB, other environment details and versions:**    
Included in the CF script.

**Steps to reproduce:**
Log into AWS. Go to Stacks dashboard. Create two stacks with same CF script in [1].

[1] - https://github.com/wso2/cloudformation-is/blob/master/cloudformation-templates/pattern-1/pattern-1-with-puppet-cloudformation.template.yml

**Comment by pasindujw** [comment]
Moving forward from there, I've received the following error;
**is-carbon-9443 already exists in stack**

**Comment by kasunbg** [comment]
OK.. What is is-carbon-9443? :)

**Comment by pasindujw** [comment]
According to [1] from the CF Script, is-carbon-9443 refers to a name of an AWS "ElasticLoadBalancingV2" Load Balancer.

[1] - https://github.com/wso2/cloudformation-is/blob/91f7ea06d33b144cfae4758c6030eaed2c9e9831/cloudformation-templates/pattern-1/pattern-1-with-puppet-cloudformation.template.yml#L535
