### ISSUE TITLE
Test case failure message in report should be simple

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/testgrid#490]
**Description:**
As per the discussion in https://github.com/wso2/testgrid/pull/489, we do not need to persist the entire failure message in the database as it is not required in the report (we can log it instead). The idea is that the report will be used to get a quick idea about the product while the logs will be used to trace an issue.

**Comment by kasunbg** [comment]
If the response data is a SOAP fault, which is the case when a test case fails for a given SOAP request, then we can extract the failure message from the soap fault itself.

See the faultstring in the below soap response which is an actual response sent by the 'DeleteGoogleIDp' test case of identity scenario scripts.

![image](https://user-images.githubusercontent.com/936037/36294586-d0201faa-1307-11e8-8b4f-0175be3a83e9.png)

**Comment by azinneera** [comment]
We can remove the Sampler data from the failure message. Then we will have the response code, response message and the response data.
Eg: {
"Status code": "500", 
"Response Message": "Internal Server Error", 
"Response Data": "<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <soapenv:Fault>
         <faultcode>soapenv:Server</faultcode>
         <faultstring>com.ctc.wstx.exc.WstxParsingException: Unexpected close tag &lt;/xsd:properties&gt;; expected &lt;/xsd:value&gt;. at [row,col {unknown-source}]: [32,31]</faultstring>
         <detail />
      </soapenv:Fault>
   </soapenv:Body>
</soapenv:Envelope>"

WDYT?

**Comment by kasunbg** [comment]
+1
