### ISSUE TITLE
Support passing environment variables into scripts from ShellScriptProvider

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#491]
**Description:**
ATM, we do not support passing environment variables into the shell scripts executed by testgrid via ShellScriptProvider. 

We need to provide this support. We can take test-scripts/tomcat-deployment as the base for this purpose. This has an `infra.sh` that calls AWS via the AWS CLI. The CLI require access credentials which can be passed as environment variables. [1]

We can pass the env variables at the script execution time or via a properties file. 
If it is a properties file, then we need to inject properties file parsing logic into the `infra.sh`. I think properties file is the way to go.

[1] https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Affected Product Version:**
0.9.0-m13

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
See above.

**Related Issues:**
N/A

**Comment by azinneera** [comment]
Since we are executing shell scripts for OpenStack, we can feed the openrc.sh file as an input parameter and source it inside the shell script. AWS does not need to use environment variables for credentials. We can make use of PropertiesFileCredentialsProvider.
