### ISSUE TITLE
Send an email for each job run to relevant teams

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#508]
**Description:**
We need a notification mechanism for testgrid. Whenever a build run in testgrid, we need to inform relevant parties (via builder@wso2.org mailing list?) about the failure.

I think the most-suited notification mechanism is _email_. We can get a email server from infra folks I believe. Jenkins already support [sending emails](https://wiki.jenkins.io/display/JENKINS/Email-ext+plugin#Email-extplugin-BuildStatus) via a plugin. We can use that via the [Jenkinsfile](https://wiki.jenkins.io/display/JENKINS/Email-ext+plugin#Email-extplugin-PipelineExamples) to send the mail.

**Affected Product Version:**
0.9.0-m13

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**

**Comment by harshanL** [comment]
Mail configuration is done. Need to configure the email template and relevant email addresses in the job configuration.

**Comment by yasassri** [comment]
This is already fixed.
