### ISSUE TITLE
Infrastructure parameters should be customizable for each test plan

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/testgrid#513]
**Description:**
Currently, for each test run, we prepare infrastructure parameters by producing combinations from all parameter value sets. in other words, every product will have to support every combination
This is not practical in scenarios like kubernetes deployments where OS is not a significant factor to change. There can be also instances where certain versions are not applicable to certain products. 

TestGrid needs to support customizations for input parameter values and provide a proper mechanism for preview what parameters are applicable to what test run.For that the test-grid.yaml needs to support inclusions and exclusions of values/groups. 

**Suggested Labels:**
Type/Improvement
Priority/High

**Steps to reproduce:**
Generate test plan command will use all values in Infrastructure_parameter table to create combinations.

**Comment by sameerawickramasekara** [comment]
@kasunbg Please add proper labels and Milestone

**Comment by pasindujw** [comment]
This is fixed. Hence closing.
