### ISSUE TITLE
Add a new EBS volume with higher capacity to TestGrid Prod

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#522]
**Description:**
TestGrid Prod is running low on disk space. We need to increase the disk size. 

One option is to mount a new EBS volume, and copy the content from all disk to the new disk. This is urgent!

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
The Testgrid Jenkins master node goes offline if the disk space is low.

**Related Issues:**

**Comment by harshanL** [comment]
Increased the EBS volume to 25GB.
