### ISSUE TITLE
Take the infrastructure template directory location from testgrid.yaml

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#527]
**Description:**
ATM. we have hard-coded the location of a given infrastructure provisioner within the [Jenkinsfile](https://github.com/wso2/testgrid/blob/70e6677b99c53b32cfca07d1b091b72f401b2bab/jenkins/pipelines/Jenkinsfile#L68). This is not correct.

But, we should rather read the [directory location](https://github.com/azinneera/cloudformation-is/blob/master/infrastructure-build-plans/single-node-infra.yaml#L12) from the [infrastructureConfig/provisioners[0]/dir](https://github.com/wso2/testgrid/blob/master/common/src/main/java/org/wso2/testgrid/common/config/DeploymentConfig.java#L78) location instead.

**Affected Product Version:**
0.9.0-m14

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
The infrastructureRepository and deploymentRepository inputs should be the root directory of the cloned git repository. Testgrid shouldn't be aware where exactly the template files are located. These should be read from testgrid.yaml.

**Related Issues:**
N/A

**Comment by pasindujw** [comment]
@kasunbg Although the location is hard-coded in jenkinsfile, we take those details from Build-API as inputs. So wouldn't that sufficient? :)

**Comment by pasindujw** [comment]
This is fixed. Hence closing.
