### ISSUE TITLE
Adding AMIs to TestGrid AWS account for necessary infrastructure combinations

### ISSUE THREAD

**Issue by pasindujw** [wso2/testgrid#543]
**Description:**
(Considering the scenarios where AWS as infrastructure provider..)
TestGrid has an AMI Mapper which looksup for matching AMI in TestGrid AWS and pass ami-id to CF script (if it requests). 
In future, its the external users whom will be sharing their AMIs, but ATM for the first-cut, in TestGrid AWS account, we will be needing to add and maintain a set of AMIs which has necessary infrastructure facilities (currently OS and JDK) pre-installed.

AMIs will be created for following infrastructure combinations {Each OS} x {Each JDK}.
OS:  Ubuntu, CentOS
JDK: OracleJDK 8 and 9.

**Comment by kasunbg** [comment]
@pasindujw it's not clear what the issue is. :)

**Comment by pasindujw** [comment]
@kasunbg Please check now.

**Comment by pasindujw** [comment]
Please close this as the above AMIs and AMIs needed for WSO2-APIM (as instructed in https://github.com/wso2/cloudformation-apim ReadMe.md)  are added.

**Comment by pasindujw** [comment]
Please change the status label as Completed.
