### ISSUE TITLE
Persist infrastructureConfig details in the database along with the TestPlan

### ISSUE THREAD

**Issue by harshanL** [wso2/testgrid#552]
**Description:**
Currently, testgrid does not persist infrastructureConfig details in the database. We have to stick to test-plan.yaml file due to this reason as we need infrastructureConfig information during testplan execution phase.

**Affected Product Version:**
0.9.0-m16

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
#514

**Comment by kasunbg** [comment]
I believe this is implemented. We capture the infra parameters of a given test-plan via the  'infra_parameters' column of the test_plan table.
