### ISSUE TITLE
Run APIM testgrid build job for each build in WSO2 Jenkins CI

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#557]
**Description:**
We need to periodically run product-apim build for each build that has happened in WSO2 Jenkins instance. [1]. The latest stable distribution ZIP can be downloaded from [1].

When this is in place, whenever a build has failed, we need to generate the report and send it as a mail. 

Approach:
We can use the periodic [build trigger](https://www.safaribooksonline.com/library/view/jenkins-the-definitive/9781449311155/ch05s05.html) support available in the testgrid jenkins instance for this purpose. 

[1] https://wso2.org/jenkins/job/products/job/product-apim_2.x/lastStableBuild/org.wso2.am$wso2am/

**Affected Product Version:**
0.9.0-m16

**Steps to reproduce:**
N/A

**Related Issues:**
#509

**Comment by harshanL** [comment]
@kasunbg : Currently, APIM CF scripts are based on pre-packaged AMIs. Thus, in order to complete this we need to either separate APIM deployment from AMI (as in Identity Server scripts) or have another job to create an AMI based on latest build (that's what Imesh has suggested).

**Comment by kasunbg** [comment]
@harshanL, I see. So, I guess we need an immediate workaround solution, and a long-term solution.

For the immediate solution, we can use pre-packaged AMIs. At build time, we should add the new pack into the AMI. Since AMIs are immutable, we will have to create a new AMI based on the pre-packaged AMI.
This new AMI will be the input into the cloudformation scripts.

**Comment by kasunbg** [comment]
This is done.
