### ISSUE TITLE
Support infra-param JDK for Oracle-JDK8 and Oracle-JDK9

### ISSUE THREAD

**Issue by pasindujw** [wso2/testgrid#560]
**Description:**
TestGrid needs to support OracleJDK 8 and OracleJDK9 as the infra-param JDK and then provide infra-combinations for each of those..

**Suggested Labels:**
Priority/Highest Type:Improvement

**Suggested Assignees:**
pasindujw

**Comment by pasindujw** [comment]
Created necessary AMIs with relevant tags to achieve the $subject.

**Comment by harshanL** [comment]
Current AMIs have not configured JAVA_HOME for the root user. Thus, carbon server is not starting up since it is running as the root user.

**Comment by harshanL** [comment]
+1.
