### ISSUE TITLE
TestPlan status update task to set the appropriate states to TestPlans

### ISSUE THREAD

**Issue by harshanL** [wso2/testgrid#573]
**Description:**

Currently, when someone aborts a jenkins pipeline job, the created test-plans, test-scenarios and testcases will be in invalid states (running/pending ect) forever. Thus, we need a way to set appropriate states to testplans, test-scenarios and testcases as it affects the user experience in such cases. 

**Affected Product Version:**
0.9.0-m16

**Comment by azinneera** [comment]
Fixed in PR #592
