### ISSUE TITLE
Prefix AMI tags with 'X-Testgrid-' to make them unique

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#579]
**Description:**
This is about the AMIs we use for cloudformation scripts.

Right now the AMI tags are set to the exact value present in the infrastructure_parameter database. Currently, we have these tag keys: 'DBEngine', 'DBEngineVersion', 'JDK' etc.

These are not unique to testgrid. So, to make it unique, we can prefix these with some kind of string. 
Suggested string:
`X-Testgrid-`

Some examples: `X-Testgrid-JDK`, `X-Testgrid-DBEngine`

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Cloudformation

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by pasindujw** [comment]
Why do we need to have TestGrid-unique tags? (for my knowledge :) )

**Comment by kasunbg** [comment]
@pasindujw Just noticed your comment. :) I think it's good to distinguish these tags in order to not conflict these with something else.

**Comment by kasunbg** [comment]
bump!
