### ISSUE TITLE
Rotate the AWS credentials used by Cloudformation

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#597]
**Description:**
We are heavily using AWS based saas service now. As a security best practice, we need to rotate the access keys daily/weekly. This need to be automated. So, following two credentials need to be rotated:

* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY keys

**Affected Product Version:**
0.9.0-m16

**OS, DB, other environment details and versions:**    
AWS with cloudformation scripts

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by kasunbg** [comment]
Related #639

**Comment by pasindujw** [comment]
duplicate of #639
