### ISSUE TITLE
sqlcmd not found when running MSSQL database create statements in AWS AMIs

### ISSUE THREAD

**Issue by harshanL** [wso2/testgrid#601]
**Description:**
MSSQL client utility in AMIs are not working when running sql commands from AWS user. 

**Related Issues:**
#590

**Comment by kasunbg** [comment]
Who is the AWS user?

**Comment by harshanL** [comment]
Output of "whoami" command says it is the "root" user. This was fixed by adding symbolic links to sqlcmd bin directory.
