### ISSUE TITLE
[APIM] Support the JDKs for APIM Cloudformation: Oracle-JDK 8/9/10 and OpenJDK 8/9/10

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#606]
**Description:**
We need to support Oracle-JDK 8/9/10 and OpenJDK 8/9/10 for APIM jobs. Right now, we only have kubernetes based APIM jobs. Hence, this effort will bring in multiple-JDK support for k8s deployments. 

**Affected Product Version:**
0.9.0-m17

**OS, DB, other environment details and versions:**    
APIM-2.1.0
Oracle-JDK 8/9/10 and OpenJDK 8/9/10
K8S and Docker

**Steps to reproduce:**
N/A

**Related Issues:**
#560

**Comment by azinneera** [comment]
We have APIM for cloudformation and kubernetes.

Cloudformation - This is resolved from TestGrid side with #623, #624, #626.
Kubernetes - We have to keep this on hold till the kubernetes artifacts are released with our requirements addressed.

**Comment by kasunbg** [comment]
Resolved.

**Comment by kasunbg** [comment]
We have AWS jobs as well, and these JDKs are supported there. I'll open a separate issue to track k8s progress. Thanks Asma.
