### ISSUE TITLE
Document the input and output requirements of each testgrid run-testplan step

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#622]
**Description:**
Now that we have a working system, we can start documenting what are the inputs and outputs that should be expected by infrastructure, deployment, and scenario test scripts. Immediate needs:

1. To apply config change sets, we need to know exactly the APIM profile and its associated IP address. This can be output as key-value pairs.
2. We need server-urls of each profile (store/publisher/gateway/km/tm)

**Affected Product Version:**
0.9.0-m18

**OS, DB, other environment details and versions:**    
N/A
**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by kasunbg** [comment]
We need to clearly communicate this to all product teams and installation experience team.

**Comment by harshanL** [comment]
Updated the "TestGrid Architecture and Design" doc with the content.
