### ISSUE TITLE
Add tests to infrastructure creation using shell scripts

### ISSUE THREAD

**Issue by azinneera** [wso2/testgrid#63]
**Description:**
Tests should be added to test the infrastructure creation using shell scripts

**Suggested Labels:**
Type/Task

**Suggested Assignees:**
AsmaJ

**Comment by kasunbg** [comment]
Yasassri, this is already done?

**Comment by harshanL** [comment]
This is fixed with PR: https://github.com/wso2/testgrid/pull/540
