### ISSUE TITLE
Scenario tests execution hangs

### ISSUE THREAD

**Issue by harshanL** [wso2/testgrid#630]
**Description:**
Scenario test execution hangs just after the server startup. 

**Affected Product Version:**
0.9.0-m18

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
- Generate test palns
- Execute one test-plan

**Comment by harshanL** [comment]
This was due to terminating QA-tomcat instance. It was resolved by spawning up a new instance and setting it up.

**Comment by kasunbg** [comment]
The scenario test execution should gracefully end if there is an issue such as terminated QA-tomcat instance. Shall we provide a fix to address that?

**Comment by harshanL** [comment]
Actually, it did not hang . But the process was halted due to the conditional wait in [1] which checks for the tomcat deployment. After sometime the test execution automatically fails. Thus, IMO we don't need to handle this scenario specifically.

[1]. https://github.com/wso2-incubator/identity-test-integration/blob/master/scenario01/base-setup.sh
