### ISSUE TITLE
Testgrid prod dashboard does not load

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#633]
**Description:**

I get following error message:

![image](https://user-images.githubusercontent.com/936037/38085975-48fb7770-3370-11e8-8339-62e6fcbad123.png)

Issue fixed after clearing the cookies. But, issues like this keeps happening, so we need to carefully analyze and fix the dashboard. This is a critical piece of testgrid work.

**Affected Product Version:**
0.9.0-m18

**OS, DB, other environment details and versions:**    
Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**Steps to reproduce:**
This can possibly be reproduced with stale browser data and cookies. I cleared the cookies, so we may have to identify a fix by reading the code.

**Related Issues:**
We previously had an issue due to service-worker, above is not about that as I see: #551

**Comment by azinneera** [comment]
This is not reproduced with the latest dashboard. Hence we can close this.
