### ISSUE TITLE
[Dashboard] Show the date of the test-run in the build page

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#635]
**Description:**

ATM, there's no easy way to know when the build was run in dashboard. We can find it out by looking at the date in log, but that's inconvenient. So, we should think about showing the date, and the build time in the build page itself. 

![image](https://user-images.githubusercontent.com/936037/38087072-6deecd12-3374-11e8-8f2e-d807ead24abb.png)

**Affected Product Version:**
0.9.0-m18

**OS, DB, other environment details and versions:**    
Testgrid prod

wso2is-5.4.1-LTS /default /{"JDK":"ORACLE_JDK9","OS":"UBUNTU","DBEngineVersion":"10.0","DBEngine":"mariadb"}

**Steps to reproduce:**
https://testgrid-live.private.wso2.com/testgrid/dashboard/testplans/17335f03-6289-459a-9021-0043cc4aae40

**Related Issues:**

**Comment by pasindujw** [comment]
Shows the date now..
