### ISSUE TITLE
[Dashboard] Create an admin portal to add new infrastructure parameters into the system.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#646]
**Description:**
This is a tentative task.

It's good have a admin portal to add/remove/update infrastructure_parameter table. Right now, we have to manually go and populate the database. It's a bit cumbersome. 

**Affected Product Version:**
0.9.0-m19

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
N/A

**Related Issues:**
#283

**Comment by pasindujw** [comment]
Closing due to low priority.
