### ISSUE TITLE
Dynamically create QA resources

### ISSUE THREAD

**Issue by harshanL** [wso2/testgrid#654]
**Description:**

In the existing testgrid setup, QA resources such as tomcat instances are static. This creates a limitation when running parallel job executions. Furthermore, having too many static instances is not a scalable solution. Thus, we need a mechanism to dynamically spawn such required instances on the fly.

**Related Issues:**

#567, #649, #528, #317

**Comment by pasindujw** [comment]
Not applicable ATM.
