### ISSUE TITLE
Fetch product wso2carbon.log and archive them during test-runs

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#660]
**Description:**
Currently, only log we have is the client-side logs. That is, 

1. Infrastructure (AWS) creation logs
2. Deployment creation logs
3. Jmeter run logs

This is not enough to debug and fix the issues testgrid reports. Having carbon logs is a must. 

We need to plan how we are going to do that. The deployments can get quite complex, and there can be loads of WSO2 and other servers spawned by infrastructure creation scripts.

We need a mechanism to consume all these log files and archive them along with the testgrid _test-run.log_.  Currently, test-run.log is stored in S3. We can store the server logs alongside.

Initially, we can only focus on archiving the WSO2 server logs at AWS. As the next step, we can focus on archiving other logs such as logs from mysql, nginx servers etc.

This is a critical feature.

**Affected Product Version:**
0.9.0-m20

**OS, DB, other environment details and versions:**    
AWS

**Steps to reproduce:**
N/A

**Related Issues:**
#411

**Comment by harshanL** [comment]
For this purpose, we have to either create our agent service which returns or persists the files we want or try to set automatic upload of files to an s3 bucket when the instance is being terminated. Following link [1] would be useful.

[1]. https://blog.jayway.com/2014/09/12/automatic-backup-of-log-files-to-s3-from-ec2-instances/

**Comment by pasindujw** [comment]
This is fixed.
