### ISSUE TITLE
AWS Provider should be able to execute multiple scripts.

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/testgrid#67]
**Description:**
AWS Provider makes an assumption that there is only one CF script, that should be changed to handle multiple scrips.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
Sameera Wickramasekara

**Comment by pasindujw** [comment]
Not applicable ATM. (We do the parallelism for the whole run-testplan phase)
