### ISSUE TITLE
Dashboard does not show the log content until completion of build job

### ISSUE THREAD

**Issue by azinneera** [wso2/testgrid#671]
**Description:**

Both dev and prod dashboards does not show the logs till end of the pipeline execution. This is because the logs are taken from an s3 location and the log files are being uploaded only in the post block. This should be changed to upload the log files to the s3 location at the end of each test plan.

**Suggested Labels:**

Type/Improvement, Priority/Highest, Severity/Critical

**Suggested Assignees:**

AsmaJ

**Comment by azinneera** [comment]
Resolved by uploading the log files after each test-plan stage.

**Comment by kasunbg** [comment]
@azinneera shall we send a PR as well? We dont want to stale the Jenkinsfiles in git. :)

Btw, we should not maintain per-job Jenkinsfiles IMO. That'll be hard to manage as is evident in this issue. :) We should try to have Jenkinsfile representing all jobs. The list of infra/scenario repos can be provided as external inputs. Failing that, we can go for one Jenkinsfile per infrastructure type. ie. for Cloudformation and K8S.

WDYT?
