### ISSUE TITLE
Get initial scenario test scripts for EI 6.1.1 and 6.2.0

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#683]
**Description:**
We are running dummy scripts for EI ATM. We initially need to have at least two or three good real-world usecases that can cover majority of EI's functionality.

This is actually owned by the STL team. I just reported in here to keep track of it from testgrid side.

CC: @chaminda @dilinisg 

**Affected Product Version:**
0.9.0-m21

**OS, DB, other environment details and versions:**    
0.9.0-m21

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by pasindujw** [comment]
This is fixed.
