### ISSUE TITLE
Improve the performance of data retrieval.  

### ISSUE THREAD

**Issue by lasanthaDLPDS** [wso2/testgrid#692]
**Description:**
With the current implementation of TESTGRID, it is required to refresh returning data from queries. Because query will retrieve data from the cache and if we completely bypass the cache for updating the database, the state held by the cache won't be updated to the updated database state. Hence in order to avoid this inconsistency, once after data retrieve, TESTGRID refreshing data. It will be affected the performance. Therefore it is required to modify the designing to resolve the performance impact.

**Affected Product Version:**
0.9.0-m21

**Comment by pasindujw** [comment]
Closing since no major impact ATM.
