### ISSUE TITLE
Need a mechanism to execute pre, post scripts before and after scenario test execution

### ISSUE THREAD

**Issue by harshanL** [wso2/testgrid#712]
**Description:**

We need to support executing pre & post scripts prior and post execution of all scenario tests. This will be useful in cases such as configuring /etc/hosts file of test executing machine to point the WSO2 server instances. 

**Affected Product Version:**
0.9.0-m22

**Related Issues:**
#649

**Comment by azinneera** [comment]
Closing since resolved by #756. Updated the PR.
