### ISSUE TITLE
Enrich the list of infrastructure we support

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#721]
**Description:**
ATM, we only run following infrastructure:

OS: Ubuntu 16.04 and CentOS 7.4
JDK: OpenJDK 8 and Oracle JDK 8
DB: Postgres 9.6.1, 10.3, mysql 5.7, oracle 11.2, sqlserver 13.00, mariadb 10.0.32

This is not comprehensive enough. We need to add rest of the OSes, JDKs, and Databases. We need to more DBs, JDKs and OSes.

We can add some of the infrastructure by simply adding an entry into infrastructure_parameter table. This can be done for other CentOS versions such as 6.6, adding other Database versions such as Mysql 5.6, Oracle 12g etc.

Therefore, we need to first add the infrastructures we can easily configure via infrastructure_param table.

Rest can follow course afterwards.

**Affected Product Version:**
0.9.0-m22

**Related Issues:**
N/A

**Comment by kasunbg** [comment]
cc @tharindu1992

**Comment by pasindujw** [comment]
Closing since now the product-teams/script providers are responsible to add new infrastructures to incorporate with TestGrid. :)
