### ISSUE TITLE
Support Microsoft Windows Server infrastructure in testgrid

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#724]
**Description:**
Now that we have Ubuntu 16.04 and CentOS 7.4 (#483) in testgrid, we need to put our focus on Microsoft Windows. For Windows, we can initially target its server versions. 

We can possibly start with Windows server 2016 and 2012 R2. [1] Older versions are still in use though. 

One major challenge when doing this is that we do not have the necessary installation scripts to support Windows. Since timeline for Windows-supported installation scripts is a bit too far for IET team right now, we have to come up with a rudimentary script that can do this. At a minimum, it can be a single node product deployment of IS/APIM.

**Deliverables:**
* Working installation scripts for a minimal single-node product deployment. We can choose either IS/APIM
* A Testgrid job that can execute the installation scripts to provision a product deployment, and then run scenario test scripts against that deployment.

[1] https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions#Server_versions
 

**Affected Product Version:**
0.9.0-m22

**OS, DB, other environment details and versions:**    
Windows Server 2016, 2012 R2.

**Related Issues:**
#483

**Comment by pasindujw** [comment]
This is completed.
