### ISSUE TITLE
Alternative directory created for same TG job with a suffix and scenario tests are not running

### ISSUE THREAD

**Issue by charithag** [wso2/testgrid#757]
**Description:**
When already running Jenkins job terminated forcefully by user and once new job created, secondly created job create a new directory with suffix and won't have test plans. Due to that reason, all test plans will be ignored and job completes without running test plans by making it false positive.

For example, if we interrupted wso2is-5.4.1-LTS build, and then triggered another build right after, new job is running on Jenkins in /testgrid/testgrid-home/jobs/wso2is-5.4.1-LTS@2 location though it should run in /testgrid/testgrid-home/jobs/wso2is-5.4.1-LTS directory.

**Affected Product Version:**
0.9.0-m26

**OS, DB, other environment details and versions:**    
Ubuntu 16.04 LTS, Jenkins 2.89.2

**Steps to reproduce:**
1. Start jenkins job for a product
2. Interrupt the job from jenkins UI
3. Trigger another build for same product

**Expectation**: New build should also use the same job directory as previous
**Actual**: New directory created with a suffix

**Comment by lasanthaDLPDS** [comment]
Hi all,

As per the investigations we observed its happening because of an issue in the Jenkins side. You can find further details by referring following resources. [1], [2] 

[1] - https://issues.jenkins-ci.org/browse/JENKINS-30231
[2] - https://issues.jenkins-ci.org/browse/JENKINS-10615
