### ISSUE TITLE
testgrid-prod-deploy pipeline fials due to missing artifact

### ISSUE THREAD

**Issue by azinneera** [wso2/testgrid#758]
**Description:**

testgrid-prod-deploy pipeline fails when trying to copy the wrong artifact. The correct artifact should be added to the copyArtifacts filter and the artifact should be archived in testgrid job as well.

**Suggested Labels:**

Type/Bug

**Suggested Assignees:**

AsmaJ

**Comment by kasunbg** [comment]
Now, you can add the labels and assignees yourself since you already got commit privileges.. :)
