### ISSUE TITLE
[Dashboard] [intermittent] Displays incorrect output when we access Test Grid dashboard directly

### ISSUE THREAD

**Issue by lasanthaDLPDS** [wso2/testgrid#771]
**Description:**

Sometimes when we access Test Grid dashboard URLs directly, it displays incorrect output. We suspect its because of browser cash and have to investigate further and identify the root cause.

![kgissue](https://user-images.githubusercontent.com/7247568/40602278-a31d04e2-6275-11e8-8570-fd81c6d55aca.png)

**Affected Product Version:**
Test Grid - 0.9.0-m28

**Comment by kasunbg** [comment]
Cannot reproduce.
