### ISSUE TITLE
Sort the list of scenario in dashboard by name

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#790]
**Description:**
It's a bit hard to compare two reports in TG dashboard because the list scenarios are shown out of order. So, we need to sort them by name.

See below:
![image](https://user-images.githubusercontent.com/936037/41132612-b0f9df32-6adf-11e8-8778-5622c589719f.png)

vs.

![image](https://user-images.githubusercontent.com/936037/41132635-c5f80698-6adf-11e8-9494-cc017115c3a6.png)

**Affected Product Version:**
m30

**OS, DB, other environment details and versions:**    
is-5.5.0-LTS build job.

**Steps to reproduce:**

**Related Issues:**

**Comment by pasindujw** [comment]
This is fixed.
