### ISSUE TITLE
Determine the AWS region based on the available AWS resources.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#793]
**Description:**
  In order to increase the parallelism of Testgrid jobs, we need to dynamically determine the AWS region we are going to use dynamically for each test-plan. Right now, we are limited to run on a pre-configured region (us-east-1). This is not scalable enough.                                                                                                                                             

**Affected Product Version:**
 0.9.0-m30                                                                                                                       

**OS, DB, other environment details and versions:**
  N/A                                                                                                      
**Steps to reproduce:**
  The region is hard-coded into the test-plans generated via generate-testplan command. We need to determine the region at run-testplan phase instead. 
The cloudformation scripts are more or less self-contained, so this should be pretty straight-forward. Few things that I think we need factor in are: 
* AMIs are maintained per-region. We need an automated mechanism like packer to copy a given AMI into all the available regions. (Use of packer is a secondary task.)
* The EC2 ssh key-pair are maintained per-region. It's better if we can upload the same key with same name to all the regions at once.
* Some regions does not have some EC2 instance types. This is probably not an issue for us. 
                                                                                                                                        
**Related Issues:**
 Part of #528

**Comment by harshanL** [comment]
As I've mentioned in the issue [1], We could use NATs as the hard limit (5 per region) as the base determiner for switching to the next available region.

[1]. https://github.com/wso2/testgrid/issues/528

**Comment by kasunbg** [comment]
@harshanL 
Let's take NAT gateways into account as well. That's not the only factor though because not all CFN scripts require NAT gateways. 

So, we have to read the cfn to find the resource requirements, then check what AWS regions can satisfy them. Off the top of my head, following resource types needs to be factored in:

1. RDS instances - 40 per region
2. EC2 instances - There are limits based on instance type here. For ex. m4.large can only have 20 or so. We increased the limits for testgrid account.
3. ELB
4. Cloudformation - 200 stacks per region. There's a stack-set as well, we shud see how it can help us.
5.  VPC - 5 per region by default. NAT gateway and other limits also apply.

@azinneera  IMO, initial impl does not need to concern all of these. May be we can focus on VPC, EC2, and RDS limits first. wdyt?

**Comment by harshanL** [comment]
@kasunbg : We have already increased VPC limit to 20 for 5 regions. However, I think we need a NAT gateway per stack or we need to find a way to share NATs across stacks if possible.

**Comment by azinneera** [comment]
@kasunbg: the installation experience team happens to say that they use NAT Gateways in all CF scripts. Therefore, since this cannot be increased, as @harshanL said, we can take this as the base determiner.

**Comment by harshanL** [comment]
It looks like they have changed their policies. So now we could have 20 NATs. So we could use that and the number of EC2 instances. WDYT?
