### ISSUE TITLE
Verify output of the Jenkins build-job and results shown on the dashboard

### ISSUE THREAD

**Issue by lasanthaDLPDS** [wso2/testgrid#796]
**Description:**
As per result is shown on the dashboard, the timestamp of the last build in the product(Home) page significantly differs from the timestamp of the last build in the infra combinations. But it should be same, hence verify the output of the Jenkins build-job and results shown on the dashboard.

**Affected Product Version:**
 0.9.0-m30

**Comment by pasindujw** [comment]
This is fixed.
