### ISSUE TITLE
Write deployment setup scripts for APIM integration test jobs

### ISSUE THREAD

**Issue by pasindujw** [wso2/testgrid#812]
**Description:**
In order to run integration tests for APIM, TestGrid needs appropriate deployment setup scripts.
The deployment pattern will be only 'single-node' since this is used to test integration tests.

**Suggested Labels:**
New feature, Priority High

**Suggested Assignees:**
KasunG

**Affected Product Version:**
m31
**OS, DB, other environment details and versions:**    
N/A
**Steps to reproduce:**
N/A

**Related Issues:**
#817

**Comment by kasunbg** [comment]
Cloudformation script with userdata section can be found here: https://github.com/wso2/testgrid/blob/master/jobs/intg-test-resources/wso2-intg-test-cfn.yaml
