### ISSUE TITLE
Extract surefire reports and process integration test status

### ISSUE THREAD

**Issue by pasindujw** [wso2/testgrid#815]
**Description:**
After running integration tests, we need to parse through surefire reports and identity the integration test statuses and feed them to Testgrid database. 

**Suggested Labels:**
New feature, Priority High

**Suggested Assignees:**

**Affected Product Version:**
m31
**OS, DB, other environment details and versions:**    
N/A
**Steps to reproduce:**
N/A

**Related Issues:**
#817

**Comment by kasunbg** [comment]
Fixed via https://github.com/wso2/testgrid/pull/829
