### ISSUE TITLE
Automate the testgrid AMI creation

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#853]
**Description:**
ATM, we create the AMIs manually. This has consumed a massive amount of time, and has lead to major inconsistencies between AMIs. Therefore, we need to automate this work.

Packer is the obvious go-to choice to build AMIs. Best yet, it supports both Linux, and Windows where it has figured out the intricacies of windows OS. Therefore, we need to implement solution asap for this. [1]

Somethings to keep track of:
1. Using Packer's source_ami_filter to find the source AMI.
2. The tags in the source AMI must be present in the new AMI as well.
3. Have a common user for unix-like OSes

Our AMIs typically have:
1. sql-drivers at ~/sql-drivers
2. JDKs at xxxx
3. cat /etc/environment that map the JDK names (ORACLE_JDK8, OPEN_JDK8) to dir locations.
4. python3 and pip3
5. Maven (for intg tests)
6. SSH server - windows dont have one by default

[1] https://www.packer.io/intro/getting-started/build-image.html 

**Affected Product Version:**
m34

**OS, DB, other environment details and versions:**    
Needed for CentOS, Windows, Ubuntu AMI.
AWS EC2

**Related Issues:**
N/A

**Comment by pasindujw** [comment]
This is fixed now.
