### ISSUE TITLE
Optimize integration test build time.

### ISSUE THREAD

**Issue by yasassri** [wso2/testgrid#874]
**Description:**

Currently with 3 parallel executors and 12 test plans test execution takes 7+ hours to run. We need to optimize this as much as we can. Following are the time consuming operation.

1. Dependency downloading for tests. 
2. Stack creation.

I can think of few ways to optimize dependency downloading time.

1. Have a mirrored nexus repo in the same AWS region.
2. Burn the dependencies into the AMI.
3. Have a m2 repo as a NFS and mount to each instance.

We need to do some research and see what else we can optimize.

**Comment by pasindujw** [comment]
We can also haven a maven repository in the S3 and point there from the pom.xml files as well.
Please refer : 
[https://www.yegor256.com/2015/09/07/maven-repository-amazon-s3.html](url)

**Comment by yasassri** [comment]
@kasunbg Any thoughts?

**Comment by kasunbg** [comment]
@yasassri,
Most time consuming operation is actually the test running time IMO. Stack creation happens in 5-10 mins for CentOS. Dependency download time can be a concern. Do we have numbers to see how much time is spent on this? 

Assuming we need to do this, please find my thoughts on the options presented:

> 
> Have a mirrored nexus repo in the same AWS region.

This makes sense. Having a mirrored repo within the same availability zone will improve the download time. 

However, WSO2 nexus is located in AWS itself (ap-southeast-1/singpore region). AWS has a good inter-region connectivity as well (https://www.cloudping.co/). So, I'm not sure whether we can gain a considerable improvement by moving nexus further close.

> Burn the dependencies into the AMI.
This will be hard to maintain. We'll have to maintain multiple AMIs with maven dependencies that'll become stale over-time. We can't keep maintaining these.

> Have a m2 repo as a NFS and mount to each instance.
This will have adverse effect when you scale. One single bottleneck may lead the entire pipeline to suffer.

@pasindujw, this is also a possibility, and will probably have the same time gain as the point #1 I think. In here, we'll have to add the maven-s3-wagon build extension into the pom.xml. We can automate that though.

In the end, I think it depend on actual time gain we can get.

**Comment by kasunbg** [comment]
@yasassri Following were identified above as the time consuming operations.

Dependency downloading for tests.
Stack creation.

Are we still on that? If not, shall we close this issue?

**Comment by pasindujw** [comment]
This is fixed.
