### ISSUE TITLE
[intg-tests] Skipped tests are counted as test failures

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#894]
**Description:**
Currently, we read the testng-results.xml to find the failing test cases. In there, we treat skipped tests also as test failures. This is incorrect so we need to fix.

**Affected Product Version:**
m34

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sameerawickramasekara** [comment]
Resolved via #896
