### ISSUE TITLE
Provide a way to map the dashboard test-plan and s3 storage contents

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#925]
**Description:**
Right now, the dashboard shows multiple test-plans for a given job. See: https://testgrid-live.private.wso2.com/wso2am-intg/integration-tests/test-plans/536d5bd5-8ead-47c4-8514-cb6e6e84dce4

In dashboard, a test-plan is found by its _id_ present in the dashboard URL.

![image](https://user-images.githubusercontent.com/936037/43384824-c37cd09c-93fc-11e8-8cf7-c803b2d5e547.png)

In S3, we can browse the test-plan artifacts. But in there, the folders are named a different than above. It does not has the test-plan id as the folder name. Instead, file named is based on this syntax: **<depl-pattern-name>__<infra-param-uuid>__<test-run-num>**. (This isn't wrong.)
https://s3.console.aws.amazon.com/s3/buckets/jenkins-testrun-artifacts/artifacts/jobs/wso2am-intg/builds

![image](https://user-images.githubusercontent.com/936037/43384836-cefd4686-93fc-11e8-829b-e849d9bed9a4.png)

Because of this difference, it's hard to debug issues. We cannot map between the test-plan we see in the dashboard with the artifact location in S3.

**Affected Product Version:**
m37

**Comment by pasindujw** [comment]
This is fixed now.
