### ISSUE TITLE
Organize the S3 artifacts based on build date

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#926]
**Description:**
Right now, S3 lists all the build artifacts of a given job in a flat hierarchy. This makes it hard to detect older build artifacts, and remove as necessary. So, we need to organize the items in some way. A good way is to organize based on build date.

**Affected Product Version:**
m37

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
#925

**Comment by pasindujw** [comment]
Now we are organizing each build on a separate directory which include <infra-combination><build_number> as its name. Closing the issue assuming the $subject is addressed by that :)
