### ISSUE TITLE
Incorrect Test Failure Count in Jenkins Console

### ISSUE THREAD

**Issue by malshaniS** [wso2/testgrid#965]
**Description:**

Display incorrect value for the test failure count in the Jenkins console. Even though there are failures in the test suite, failure count displays as 0 failures in the console.

Eg:
There are test failures in "EI test Module-mediator-1" test suite. Also it shows a test suite failure in test summary section.
<img width="739" alt="screen shot 2018-08-23 at 11 37 16 am" src="https://user-images.githubusercontent.com/40388545/44518053-e5a0a700-a6e6-11e8-9cb5-f2d07ac09376.png">

But in the section which shows the individual test execution summary gives the failure count as 0.
<img width="767" alt="screen shot 2018-08-23 at 11 38 33 am" src="https://user-images.githubusercontent.com/40388545/44518085-ffda8500-a6e6-11e8-86bb-2945bbf41aca.png">

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pasindujw** [comment]
This is fixed.
