### ISSUE TITLE
Incorrect Total Test Count per Suite in Jenkins Console

### ISSUE THREAD

**Issue by malshaniS** [wso2/testgrid#968]
**Description:**

Display incorrect value for the total test count in the section of result summary from TEST-TestSuite.xml.

The very first suite shows the correct total test count. But from the second suite onwards displays the sum of the previous total count and the total count itself. Therefore, it is not showing the total count per suite, but the sum of the test case count up-to current test suite.

<img width="697" alt="screen shot 2018-08-24 at 12 02 32 pm" src="https://user-images.githubusercontent.com/40388545/44569349-b302b700-a797-11e8-905c-afc2c3be507c.png">

According to the example the total of all test suites should be 1505. But that value can be seen as the total of "business-process-patches-bpel/TEST-TestSuite.xml" suite.

**Suggested Labels:**
Type/Bug

**Comment by pasindujw** [comment]
This is fixed.
